apiVersion: v1
kind: Pod
metadata:
  name: my-pod-2
  namespace: my-namespace-2
  labels:
    app: my-app
spec:
  containers:
  - name: my-container
    image: nginx:alpine
    ports:
    - containerPort: 80