apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
  labels:
    app: my-app
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    lifecycle:
      postStart:
        exec:
          command: ['sh', '-c', 'echo "1" > /usr/share/nginx/html/index.html']